version: '3'
services:
  db:
    image: mysql
    restart: always
    env_file: config.env
    command: --init-file /data/application/init.sql
    volumes:
        - ./init.sql:/data/application/init.sql
  stealer:
    build: stealer/
    command: python -u ./stealer.py
    env_file: config.env
    depends_on:
      - db
  bot:
    build: bot/
    command: python -u ./bot.py
    env_file: config.env
    #restart: always
    depends_on:
      - stealer
