CREATE DATABASE IF NOT EXISTS farfetch;
use farfetch;
CREATE TABLE IF NOT EXISTS supplies(id MEDIUMINT AUTO_INCREMENT PRIMARY KEY, search VARCHAR(256) NOT NULL, name VARCHAR(256) NOT NULL, price MEDIUMINT NOT NULL, brand VARCHAR(256) NOT NULL, image VARCHAR(256) NOT NULL);
CREATE TABLE IF NOT EXISTS ontime(subject VARCHAR(16) NOT NULL UNIQUE, `status` BOOL NOT NULL DEFAULT 0);
INSERT IGNORE INTO ontime(subject) VALUES('supplies');
CREATE USER IF NOT EXISTS 'db_user'@'%' IDENTIFIED BY '1234' PASSWORD EXPIRE NEVER;
GRANT SELECT, INSERT, DELETE, UPDATE ON farfetch.* TO 'db_user'@'%';