CREATE DATABASE IF NOT EXISTS farfetch;
use farfetch;
CREATE TABLE IF NOT EXISTS supplies(id MEDIUMINT AUTO_INCREMENT PRIMARY KEY, search VARCHAR(256) NOT NULL, name VARCHAR(256) NOT NULL, price MEDIUMINT UNSIGNED NOT NULL, brand VARCHAR(256) NOT NULL, image VARCHAR(256) NOT NULL);
CREATE TABLE IF NOT EXISTS user(id BIGINT UNSIGNED PRIMARY KEY NOT NULL, top_bound MEDIUMINT UNSIGNED default 16777215 NOT NULL, bot_bound MEDIUMINT UNSIGNED default 0 NOT NULL, prefs JSON NOT NULL, mode ENUM('search', 'set_tbound', 'set_bbound') NOT NULL DEFAULT 'search', sort_order ENUM('desc', 'asc') default 'asc' NOT NULL);
CREATE TABLE IF NOT EXISTS ontime(subject VARCHAR(16) NOT NULL UNIQUE, `status` BOOL NOT NULL DEFAULT 0);
INSERT IGNORE INTO ontime(subject) VALUES('supplies');
CREATE USER IF NOT EXISTS 'db_user'@'%' IDENTIFIED BY '1234' PASSWORD EXPIRE NEVER;
GRANT SELECT, INSERT, DELETE, UPDATE, CREATE VIEW, DROP ON farfetch.* TO 'db_user'@'%';